import Header from '../components/Header/Header'
import Content from '../components/Content/Content'
import Footer from '../components/Footer/Footer'
import Link from 'next/link';
import '../public/css/global.css'

const Bijlage = () => (
    <div>
      <Header/>
      <Content>
        <h1>Bronnenlijst</h1>

      <div>
        <p><span data-contrast="auto">Holo-Light. “Microsoft Keynote HoloLens 2 at Mobile World Congress (MWC) 2019”.&nbsp;Online video clip. YouTube. YouTube,&nbsp;24&nbsp;feb.2019.&nbsp;</span><a href="https://www.youtube.com/watch?v=k5SMABo4jwM"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=k5SMABo4jwM</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Chris Davies. “HoloLens 2: The four big improvements”.&nbsp;Feb 25, 2019, 1:20 pm CST.&nbsp;</span><a href="https://www.slashgear.com/microsoft-hololens-2-four-key-improvements-comfort-fov-holograms-25567353/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.slashgear.com/microsoft-hololens-2-four-key-improvements-comfort-fov-holograms-25567353/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Susan Michalak. “Guidelines for Immersive Virtual Reality Experiences”.&nbsp;July 3, 2017.&nbsp;</span><a href="https://software.intel.com/en-us/articles/guidelines-for-immersive-virtual-reality-experiences"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://software.intel.com/en-us/articles/guidelines-for-immersive-virtual-reality-experiences</span></span></a><span data-contrast="none">&nbsp;</span><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">timoni&nbsp;west. “UX pointers for VR design”.&nbsp;Nov 10, 2015.&nbsp;</span><a href="https://medium.com/@timoni/ux-pointers-for-vr-design-dd52b718e19"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://medium.com/@timoni/ux-pointers-for-vr-design-dd52b718e19</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Wikipedia. “Perfetti Van Melle”&nbsp;13&nbsp;nov&nbsp;2015.&nbsp;</span><a href="https://nl.wikipedia.org/wiki/Perfetti_Van_Melle"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://nl.wikipedia.org/wiki/Perfetti_Van_Melle</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft. “Introducing instinctual interactions”.&nbsp;11-04-2019.&nbsp;</span><a href="https://docs.microsoft.com/nl-nl/windows/mixed-reality/interaction-fundamentals"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/nl-nl/windows/mixed-reality/interaction-fundamentals</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Uptake. “How AI is Making Predictive Maintenance a Reality for the Industrial IoT”.&nbsp;June 11, 2018.&nbsp;</span><a href="https://www.uptake.com/blog/how-ai-is-making-predictive-maintenance-a-reality-for-the-industrial-iot"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.uptake.com/blog/how-ai-is-making-predictive-maintenance-a-reality-for-the-industrial-iot</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Kim van&nbsp;Veldhuijzen&nbsp;en Robin van&nbsp;Zessen. “Co-Design Methods”.&nbsp;</span><a href="https://codesignmethods.com/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://codesignmethods.com/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">HAN University of Applied Sciences - Amsterdam University of Applied Sciences. “CMD Methods Pack: Find a combination of research methods that suit your needs”.&nbsp;</span><a href="http://cmdmethods.nl/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">http://cmdmethods.nl/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft HoloLens. “Introducing Dynamics 365 Remote Assist for HoloLens 2 and mobile devices”.&nbsp;24&nbsp;feb.2019.&nbsp;</span><a href="https://www.youtube.com/watch?v=J-C6GE2gFYw"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=J-C6GE2gFYw</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft Dynamics 365. “Chevron uses Dynamics 365 Remote Assist and HoloLens to improve performance”.&nbsp;18&nbsp;sep.2018.&nbsp;</span><a href="https://www.youtube.com/watch?v=rbL8H2lyC8Q"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=rbL8H2lyC8Q</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">CRAatHDA. “IoT Assistance in a Smart Factory using Microsoft HoloLens with Mixed Reality”.&nbsp;24&nbsp;nov.2017.&nbsp;</span><a href="https://www.youtube.com/watch?v=MeX8YWHhxfE"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=MeX8YWHhxfE</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Educba. “Machine Learning vs Neural Network”.&nbsp;</span><a href="https://www.educba.com/machine-learning-vs-neural-network/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.educba.com/machine-learning-vs-neural-network/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p>&nbsp;<br /><span data-contrast="auto">Chris Nicholson. “Artificial Intelligence (AI) vs. Machine Learning vs. Deep Learning”.&nbsp;</span><a href="https://pathmind.com/wiki/ai-vs-machine-learning-vs-deep-learning"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://pathmind.com/wiki/ai-vs-machine-learning-vs-deep-learning</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Unity. “WMR input and interaction concepts”.&nbsp;2019-12-16.&nbsp;</span><a href="https://docs.unity3d.com/Manual/wmr_input_types.html"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.unity3d.com/Manual/wmr_input_types.html</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft. “Mixed reality capture for developers”.&nbsp;02/24/2019.&nbsp;</span><a href="https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-capture-for-developers"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-capture-for-developers</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">ELEKSsoftware. “ELEKS' experiment: Mixed Reality HoloLens Solution for Streamlined Shelf Management”.&nbsp;22 jun. 2017.&nbsp;</span><a href="https://www.youtube.com/watch?v=RgMzdJR5d_c"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=RgMzdJR5d_c</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Ron Dagdag. “Image Recognition in&nbsp;#Hololens&nbsp;using Microsoft&nbsp;#CognitiveServices”.&nbsp;26&nbsp;sep.&nbsp;2016.&nbsp;</span><a href="https://www.youtube.com/watch?v=7Qz6PDKgwaM"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=7Qz6PDKgwaM</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">SARAH ROWE. “Spatial Mapping Explained: Your Guide to How Augmented Reality Works”.&nbsp;DECEMBER 19 2018.&nbsp;</span><a href="https://circuitstream.com/blog/spatial-mapping/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://circuitstream.com/blog/spatial-mapping/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Google AR &amp; VR. “Glass Enterprise Edition 2: A hands-free device for smarter and faster hands-on work”.&nbsp;20&nbsp;mei2019.&nbsp;</span><a href="https://www.youtube.com/watch?v=5IK-zU51MU4"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=5IK-zU51MU4</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft. “MixedReality-WebRTC”.&nbsp;Github.&nbsp;</span><a href="https://github.com/microsoft/MixedReality-WebRTC"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://github.com/microsoft/MixedReality-WebRTC</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Kranky&nbsp;Geek. “Microsoft UWP WebRTC update and RTC for the&nbsp;Hololense”.&nbsp;16&nbsp;nov.&nbsp;2018.&nbsp;</span><a href="https://www.youtube.com/watch?v=8sRluA_hrtc"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=8sRluA_hrtc</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft HoloLens. “Microsoft HoloLens: 3&nbsp;HoloStudio&nbsp;UI and Interaction Design Learnings”.&nbsp;29&nbsp;sep.2016.&nbsp;</span><a href="https://www.youtube.com/watch?v=sX6yKHmN1qM"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.youtube.com/watch?v=sX6yKHmN1qM</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft. “Case study - 3&nbsp;HoloStudio&nbsp;UI and interaction design learnings”.&nbsp;03/21/2018.&nbsp;</span><a href="https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-3-holostudio-ui-and-interaction-design-learnings"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/en-us/windows/mixed-reality/case-study-3-holostudio-ui-and-interaction-design-learnings</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft Azure. “Snelstartgids:&nbsp;een&nbsp;unit HoloLens-app&nbsp;maken&nbsp;die&nbsp;gebruikmaakt&nbsp;van&nbsp;ruimtelijke&nbsp;ankers&nbsp;van Azure”.&nbsp;24-02-2019.&nbsp;</span><a href="https://docs.microsoft.com/nl-nl/azure/spatial-anchors/quickstarts/get-started-unity-hololens"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/nl-nl/azure/spatial-anchors/quickstarts/get-started-unity-hololens</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft Azure. “Zelf&nbsp;studie:&nbsp;ruimtelijke&nbsp;Azure-ankers&nbsp;delen&nbsp;in&nbsp;sessies&nbsp;en&nbsp;apparaten”.&nbsp;24-02-2019.&nbsp;</span><a href="https://docs.microsoft.com/nl-nl/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/nl-nl/azure/spatial-anchors/tutorials/tutorial-share-anchors-across-devices?tabs=VS%2CAndroid</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Microsoft. “Spatial mapping in Unity”.&nbsp;03/21/2018.&nbsp;</span><a href="https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping-in-unity"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://docs.microsoft.com/en-us/windows/mixed-reality/spatial-mapping-in-unity</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Jakob Nielsen. “Interviewing Users”.</span><span data-contrast="auto">&nbsp;July 25, 2010.&nbsp;</span><a href="https://www.nngroup.com/articles/interviewing-users/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.nngroup.com/articles/interviewing-users/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Jakob Nielsen. “First Rule of Usability? Don't Listen to Users”.&nbsp;August 4, 2001.&nbsp;</span><a href="https://www.nngroup.com/articles/first-rule-of-usability-dont-listen-to-users/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.nngroup.com/articles/first-rule-of-usability-dont-listen-to-users/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-contrast="auto">Christian Rohrer. “When to Use Which User-Experience Research Methods”.&nbsp;October 12, 2014.&nbsp;</span><a href="https://www.nngroup.com/articles/which-ux-research-methods/"><span data-contrast="none"><span data-ccp-charstyle="Hyperlink">https://www.nngroup.com/articles/which-ux-research-methods/</span></span></a><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
        <p><span data-ccp-props="{&quot;201341983&quot;:0,&quot;335559739&quot;:160,&quot;335559740&quot;:259}">&nbsp;</span></p>
      </div>

      </Content>
      <Footer/>
    </div> 
  );
  
  export default Bijlage;